language:
- python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5-dev'
- 'pypy'
install:
- pip install hypothesis
- pip install coveralls
script:
- coverage run -m unittest discover
after_success:
- coveralls
notifications:
  email:
    recipients:
      - s.elahmadie@gmail.com
    on_success: change
    on_failure: always