language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5-dev'
- 'nightly'
- 'pypy'
install:
- pip install hypothesis
script:
- python -m unittest discover
notifications:
  email:
    recipients:
      - s.elahmadie@gmail.com
    on_success: change
    on_failure: always